# Generated by Django 4.2 on 2023-12-28 14:58

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('preview_image', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('price', models.SmallIntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('category', models.CharField(max_length=8)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
